/vis/scene/create
/vis/open OGLIQt
#/vis/open OGLSXm
/vis/viewer/flush
/vis/viewer/set/background white 
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 1000
/vis/geometry/set/forceLineSegmentsPerCircle all 0 200
/vis/viewer/update
/vis/viewer/set/viewpointThetaPhi 140 30 deg
/vis/ogl/set/printMode vectored
/vis/viewer/panTo 20.0 -10.0 cm
/vis/viewer/zoom 4.0
#/vis/viewer/set/style surface
#/run/beamOn 10
